replicaCount: 2

image:
  repository: kimai/kimai2
  tag: apache
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

db:
  host: ""
  name: ""
  user: ""
  password: ""
