apiVersion: v1
kind: Service
metadata:
  name: kimai
spec:
  selector:
    app: kimai
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8001
  type: {{ .Values.service.type }}
