name: Application Deploy

on:
  workflow_run:
    workflows: ["Infrastructure Deploy"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: tf-output
          path: .

      - name: Set variables from Terraform outputs
        id: vars
        run: |
          echo "EKS_CLUSTER_NAME=$(jq -r .eks_cluster_name.value tf-output.json)" >> $GITHUB_ENV
          echo "RDS_ENDPOINT=$(jq -r .rds_endpoint.value tf-output.json)" >> $GITHUB_ENV

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{ secrets.AWS_REGION }}

      - name: Deploy Kimai via Helm
        run: |
          helm upgrade --install kimai ./helm/kimai \
            --set db.host=$RDS_ENDPOINT \
            --set db.username=${{ secrets.DB_USERNAME }} \
            --set db.password=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.DB_PASSWORD_SECRET_NAME }} --query SecretString --output text) \
            --namespace kimai --create-namespace
